### ISSUE TITLE
New schema updates for Logon attempts after receipt of malicious e-mail

### ISSUE THREAD

**Issue by richlilly2004** [microsoft/MTP-AHQ#1]
Needs to be updated to the following due to the change in the schema. Sorry, Github newb!

//Find logons that occurred right after malicious email was received
let MaliciousEmail=EmailEvents
| where MalwareFilterVerdict == "Malware" 
| project TimeEmail = Timestamp, Subject, SenderFromAddress, AccountName = tostring(split(RecipientEmailAddress, "@")[0]);
MaliciousEmail
| join (
DeviceLogonEvents
| project LogonTime = Timestamp, AccountName, DeviceName
) on AccountName 
| where (LogonTime - TimeEmail) between (0min.. 30min)
| take 10

**Comment by tali-ash** [comment]
Fixed
