### ISSUE TITLE
Change in schema/context for PowerShell activities after receipt of emails from known malicious sender

### ISSUE THREAD

**Issue by richlilly2004** [microsoft/MTP-AHQ#2]
Should be changed to Timestamp and new Device fields

//Find PowerShell activities right after email was received from malicious sender
let x=EmailEvents
| where SenderFromAddress =~ "MaliciousSender@example.com"
| project TimeEmail = Timestamp, Subject, SenderFromAddress, AccountName = tostring(split(RecipientEmailAddress, "@")[0]);
x
| join (
DeviceProcessEvents
| where FileName =~ "powershell.exe"
//| where InitiatingProcessParentFileName =~ "outlook.exe"
| project TimeProc = Timestamp, AccountName, DeviceName, InitiatingProcessParentFileName, InitiatingProcessFileName, FileName, ProcessCommandLine
) on AccountName 
| where (TimeProc - TimeEmail) between (0min.. 30min)

**Comment by tali-ash** [comment]
Fixed
